"""Bounded, supplementary vLLM Prometheus metric collection.

This read-only collector is reachable only through the explicitly selected
``experimental-tuning`` coordinator.  Default smoke, benchmark, comparison,
and Golden paths do not invoke it.  Server metrics are process-wide
observations and never replace Throttle's request-scoped measurements or
decision gates.

Behavioral reference reviewed with permission: Chanwit Kaewkasi,
``cogentica-ai/kvlm`` at commit
``deb6da7904922f629441132996970ae24c2c9033``.  This implementation was written
independently against the Prometheus exposition format and vLLM metric
definitions; no kvlm source was copied.
"""

from __future__ import annotations

import asyncio
import hashlib
import hmac
import ipaddress
import math
import os
import re
import struct
from dataclasses import dataclass, field
from decimal import Decimal, InvalidOperation
from types import MappingProxyType
from typing import Mapping, NoReturn, Sequence
from urllib.parse import SplitResult, urlsplit

import httpx


MAX_RESPONSE_BYTES = 1_048_576
MAX_LINES = 10_000
MAX_LINE_BYTES = 16_384
MAX_LABELS_PER_SAMPLE = 32
MAX_LABEL_VALUE_BYTES = 4_096
MAX_RECOGNIZED_SAMPLES = 4_000
MAX_OBSERVATIONS = 1_024
MAX_WINDOW_RECOGNIZED_SAMPLES = 64_000
MAX_SAFE_NUMERIC_MAGNITUDE = 9_007_199_254_740_991
SCRAPE_TIMEOUT_SECONDS = 5.0

_METRIC_NAME = re.compile(r"[A-Za-z_:][A-Za-z0-9_:]*")
_LABEL_NAME = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
_NUMBER = re.compile(
    r"[+-]?(?:(?:[0-9]+(?:\.[0-9]*)?)|(?:\.[0-9]+))"
    r"(?:[eE][+-]?[0-9]+)?"
)
_TIMESTAMP = re.compile(r"[+-]?[0-9]+")
_DNS_HOST = re.compile(
    r"(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)"
    r"(?:\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*\.?"
)
_ENCODED_CONTROL = re.compile(r"%(?:[01][0-9a-f]|7f)", re.IGNORECASE)
_SERIES_ID_KEY = os.urandom(32)
_WINDOW_SCOPE = "server_exporter_window"
_WINDOW_DECISION_EFFECT = "none"
_WINDOW_CAVEATS = (
    "Metrics describe the explicitly configured exporter and may include "
    "traffic not generated by Throttle.",
    "Observed gauge maxima are sample maxima, not guaranteed true peaks.",
    "Supplementary metrics never change Throttle decision eligibility.",
    "vLLM request-level TPOT and token-level ITL remain separate.",
    "Finished-request outcome counts are label-free classes; abort, error, "
    "repetition, missing, and unknown reasons are not treated as successful.",
    "vLLM request TPOT may record zero for one-token responses.",
    "A same-label source switch or reset between samples may be undetectable; "
    "pin collection to one exporter instance.",
)

_REQUESTS_FINISHED_FAMILY = "vllm:request_success_total"
_ALLOWED_FINISH_REASONS = frozenset({"stop", "length"})
_DISALLOWED_FINISH_REASONS = frozenset(
    {"abort", "error", "repetition"}
)
_FINISH_REASON_CLASSES = frozenset(
    {"allowed", "disallowed", "unclassified", "not_applicable"}
)

_COUNTER_FAMILIES = frozenset(
    {
        "vllm:request_success_total",
        "vllm:generation_tokens_total",
        "vllm:prompt_tokens_total",
        "vllm:num_preemptions_total",
        "vllm:num_preemptions",
    }
)
_INTEGER_GAUGES = frozenset(
    {
        "vllm:num_requests_running",
        "vllm:num_requests_waiting",
        "vllm:num_requests_swapped",
    }
)
_KV_GAUGES = frozenset(
    {
        "vllm:kv_cache_usage_perc",
        "vllm:gpu_cache_usage_perc",
    }
)
_HISTOGRAM_BASES = (
    "vllm:time_to_first_token_seconds",
    "vllm:request_time_per_output_token_seconds",
    "vllm:inter_token_latency_seconds",
    "vllm:time_per_output_token_seconds",
    "vllm:e2e_request_latency_seconds",
    "vllm:request_queue_time_seconds",
    "vllm:request_prefill_time_seconds",
    "vllm:request_decode_time_seconds",
)
_HISTOGRAM_SUMS = frozenset(f"{name}_sum" for name in _HISTOGRAM_BASES)
_HISTOGRAM_COUNTS = frozenset(f"{name}_count" for name in _HISTOGRAM_BASES)
_HISTOGRAM_OBSERVATION_NAMES = frozenset(
    {"ttft", "tpot", "itl", "e2e", "queue", "prefill", "decode"}
)
_RECOGNIZED_FAMILIES = (
    _COUNTER_FAMILIES | _INTEGER_GAUGES | _KV_GAUGES
    | _HISTOGRAM_SUMS | _HISTOGRAM_COUNTS
)

_ALIASES: Mapping[str, tuple[str, ...]] = MappingProxyType(
    {
        "itl": (
            "vllm:inter_token_latency_seconds",
            "vllm:time_per_output_token_seconds",
        ),
        "kv_cache": (
            "vllm:kv_cache_usage_perc",
            "vllm:gpu_cache_usage_perc",
        ),
        "preemptions": (
            "vllm:num_preemptions_total",
            "vllm:num_preemptions",
        ),
    }
)


class MetricsCollectionError(ValueError):
    """A fixed-code collector failure that never reflects remote input."""

    def __init__(self, code: str) -> None:
        self.code = code
        super().__init__(code)


@dataclass(frozen=True)
class _Series:
    identity: str = field(repr=False)
    scope_identity: str = field(repr=False)
    finish_reason_class: str = field(repr=False)
    value: float


@dataclass(frozen=True, slots=True)
class MetricsSnapshot:
    """An immutable, in-memory snapshot of recognized vLLM series.

    Series identities are keyed hashes and are deliberately excluded from the
    representation and public projection.  They exist only to detect a worker
    label-topology change or observed per-series counter decrease before values
    are aggregated. They cannot identify a same-label source replacement.
    """

    recognized_samples: int
    available_families: tuple[str, ...]
    _families: tuple[tuple[str, tuple[_Series, ...]], ...] = field(
        repr=False
    )

    def _family(self, name: str) -> Mapping[str, float] | None:
        for family_name, series in self._families:
            if family_name == name:
                return MappingProxyType(
                    {item.identity: item.value for item in series}
                )
        return None

    def public_summary(self) -> dict[str, object]:
        """Return only allowlisted availability metadata, never raw labels."""

        _validate_snapshot(self)
        return {
            "recognized_samples": self.recognized_samples,
            "available_families": list(self.available_families),
        }


@dataclass(frozen=True)
class MetricsWindow:
    """Supplementary server-wide observations for one measured window."""

    elapsed_seconds: float
    observations: int
    requests_finished: int | None
    output_tokens: int | None
    prompt_tokens: int | None
    preemptions: int | None
    finished_requests_per_second: float | None
    output_tokens_per_second: float | None
    prompt_tokens_per_second: float | None
    mean_ttft_ms: float | None
    mean_tpot_ms: float | None
    mean_inter_token_latency_ms: float | None
    mean_e2e_ms: float | None
    mean_queue_time_ms: float | None
    mean_prefill_time_ms: float | None
    mean_decode_time_ms: float | None
    max_requests_running: int | None
    max_requests_waiting: int | None
    max_requests_swapped: int | None
    max_kv_cache_usage_fraction: float | None
    source_families: tuple[str, ...]
    series_counts: tuple[tuple[str, int], ...]
    scope: str = _WINDOW_SCOPE
    decision_effect: str = _WINDOW_DECISION_EFFECT
    caveats: tuple[str, ...] = _WINDOW_CAVEATS
    histogram_observation_counts: tuple[tuple[str, int], ...] = ()
    metric_scope_consistent: bool | None = None
    metric_scope_count: int | None = None
    allowed_finished_requests: int | None = None
    disallowed_finished_requests: int | None = None
    unclassified_finished_requests: int | None = None

    def __post_init__(self) -> None:
        _validate_window(self)

    def to_public_dict(self) -> dict[str, object]:
        """Return a finite, label-free, JSON-compatible projection."""

        _validate_window(self)
        return {
            "scope": self.scope,
            "decision_effect": self.decision_effect,
            "elapsed_seconds": self.elapsed_seconds,
            "observations": self.observations,
            "requests_finished": self.requests_finished,
            "output_tokens": self.output_tokens,
            "prompt_tokens": self.prompt_tokens,
            "preemptions": self.preemptions,
            "finished_requests_per_second": (
                self.finished_requests_per_second
            ),
            "output_tokens_per_second": self.output_tokens_per_second,
            "prompt_tokens_per_second": self.prompt_tokens_per_second,
            "mean_ttft_ms": self.mean_ttft_ms,
            "mean_tpot_ms": self.mean_tpot_ms,
            "mean_inter_token_latency_ms": (
                self.mean_inter_token_latency_ms
            ),
            "mean_e2e_ms": self.mean_e2e_ms,
            "mean_queue_time_ms": self.mean_queue_time_ms,
            "mean_prefill_time_ms": self.mean_prefill_time_ms,
            "mean_decode_time_ms": self.mean_decode_time_ms,
            "max_requests_running": self.max_requests_running,
            "max_requests_waiting": self.max_requests_waiting,
            "max_requests_swapped": self.max_requests_swapped,
            "max_kv_cache_usage_fraction": (
                self.max_kv_cache_usage_fraction
            ),
            "source_families": list(self.source_families),
            "series_counts": dict(self.series_counts),
            "histogram_observation_counts": dict(
                self.histogram_observation_counts
            ),
            "metric_scope_consistent": self.metric_scope_consistent,
            "metric_scope_count": self.metric_scope_count,
            "allowed_finished_requests": self.allowed_finished_requests,
            "disallowed_finished_requests": (
                self.disallowed_finished_requests
            ),
            "unclassified_finished_requests": (
                self.unclassified_finished_requests
            ),
            "caveats": list(self.caveats),
        }


def _fail(code: str) -> NoReturn:
    raise MetricsCollectionError(code)


def _labels_identity(
    labels: Sequence[tuple[str, str]], *, domain: bytes
) -> str:
    digest = hmac.new(_SERIES_ID_KEY, digestmod=hashlib.sha256)
    digest.update(domain)
    for name, value in labels:
        for part in (name, value):
            encoded = part.encode("utf-8")
            digest.update(struct.pack(">I", len(encoded)))
            digest.update(encoded)
    return digest.hexdigest()


def _series_identity(labels: Sequence[tuple[str, str]]) -> str:
    return _labels_identity(labels, domain=b"series\x00")


def _scope_identity(
    metric_name: str,
    labels: Sequence[tuple[str, str]],
) -> str:
    # vLLM adds finished_reason only to request_success_total.  Every other
    # label is treated conservatively as exporter/model/engine scope.  Hashes
    # are process-keyed and never enter the public projection.
    scope_labels = tuple(
        item
        for item in labels
        if not (
            metric_name == _REQUESTS_FINISHED_FAMILY
            and item[0] == "finished_reason"
        )
    )
    return _labels_identity(scope_labels, domain=b"scope\x00")


def _finish_reason_class(
    metric_name: str,
    labels: Sequence[tuple[str, str]],
) -> str:
    if metric_name != _REQUESTS_FINISHED_FAMILY:
        return "not_applicable"
    values = tuple(
        value for name, value in labels if name == "finished_reason"
    )
    if len(values) != 1:
        return "unclassified"
    reason = values[0]
    if reason in _ALLOWED_FINISH_REASONS:
        return "allowed"
    if reason in _DISALLOWED_FINISH_REASONS:
        return "disallowed"
    return "unclassified"


def _parse_labels(line: str, position: int) -> tuple[
    tuple[tuple[str, str], ...], int
]:
    labels: list[tuple[str, str]] = []
    names: set[str] = set()
    if position >= len(line) or line[position] != "{":
        return (), position
    position += 1
    while True:
        while position < len(line) and line[position] in " \t":
            position += 1
        if position < len(line) and line[position] == "}":
            return tuple(sorted(labels)), position + 1
        match = _LABEL_NAME.match(line, position)
        if match is None:
            _fail("metrics_malformed_sample")
        name = match.group(0)
        if name in names:
            _fail("metrics_duplicate_label")
        position = match.end()
        while position < len(line) and line[position] in " \t":
            position += 1
        if position >= len(line) or line[position] != "=":
            _fail("metrics_malformed_sample")
        position += 1
        while position < len(line) and line[position] in " \t":
            position += 1
        if position >= len(line) or line[position] != '"':
            _fail("metrics_malformed_sample")
        position += 1
        value: list[str] = []
        value_bytes = 0
        while position < len(line):
            character = line[position]
            position += 1
            if character == '"':
                break
            if character == "\\":
                if position >= len(line):
                    _fail("metrics_malformed_sample")
                escaped = line[position]
                position += 1
                if escaped == "n":
                    character = "\n"
                elif escaped in {'"', "\\"}:
                    character = escaped
                else:
                    _fail("metrics_malformed_sample")
            value_bytes += len(character.encode("utf-8"))
            if value_bytes > MAX_LABEL_VALUE_BYTES:
                _fail("metrics_label_too_long")
            value.append(character)
        else:
            _fail("metrics_malformed_sample")
        labels.append((name, "".join(value)))
        names.add(name)
        if len(labels) > MAX_LABELS_PER_SAMPLE:
            _fail("metrics_too_many_labels")
        while position < len(line) and line[position] in " \t":
            position += 1
        if position < len(line) and line[position] == ",":
            position += 1
            continue
        if position < len(line) and line[position] == "}":
            return tuple(sorted(labels)), position + 1
        _fail("metrics_malformed_sample")


def _parse_sample(line: str) -> tuple[str, tuple[tuple[str, str], ...], float]:
    match = _METRIC_NAME.match(line)
    if match is None:
        _fail("metrics_malformed_sample")
    name = match.group(0)
    labels, position = _parse_labels(line, match.end())
    if position >= len(line) or line[position] not in " \t":
        _fail("metrics_malformed_sample")
    while position < len(line) and line[position] in " \t":
        position += 1
    token_end = position
    while token_end < len(line) and line[token_end] not in " \t":
        token_end += 1
    number_text = line[position:token_end]
    if number_text in {"NaN", "+Inf", "-Inf", "Inf"}:
        _fail("metrics_nonfinite_value")
    match = _NUMBER.fullmatch(number_text)
    if match is None:
        _fail("metrics_invalid_number")
    position = token_end
    if position < len(line):
        if line[position] not in " \t":
            _fail("metrics_malformed_sample")
        while position < len(line) and line[position] in " \t":
            position += 1
        if position < len(line):
            timestamp = _TIMESTAMP.fullmatch(line[position:])
            if timestamp is None:
                _fail("metrics_malformed_sample")
    try:
        exact_value = Decimal(number_text)
        value = float(exact_value)
    except (InvalidOperation, ValueError, OverflowError):
        _fail("metrics_invalid_number")
    if not exact_value.is_finite() or not math.isfinite(value):
        _fail("metrics_nonfinite_value")
    if abs(exact_value) > MAX_SAFE_NUMERIC_MAGNITUDE:
        _fail("metrics_value_out_of_range")
    if exact_value != 0 and value == 0:
        _fail("metrics_value_underflow")
    if exact_value < 0:
        _fail("metrics_negative_value")
    if name in _COUNTER_FAMILIES | _HISTOGRAM_COUNTS | _INTEGER_GAUGES:
        if exact_value != exact_value.to_integral_value():
            _fail("metrics_nonintegral_count")
    if name in _KV_GAUGES and exact_value > 1:
        _fail("metrics_invalid_kv_fraction")
    return name, labels, value


def _validate_value(name: str, value: float) -> None:
    if not math.isfinite(value) or value > MAX_SAFE_NUMERIC_MAGNITUDE:
        _fail("metrics_value_out_of_range")
    if value < 0:
        _fail("metrics_negative_value")
    if name in _COUNTER_FAMILIES | _HISTOGRAM_COUNTS | _INTEGER_GAUGES:
        if not value.is_integer():
            _fail("metrics_nonintegral_count")
    if name in _KV_GAUGES and value > 1:
        _fail("metrics_invalid_kv_fraction")


def parse_vllm_metrics(body: bytes | str) -> MetricsSnapshot:
    """Parse one bounded Prometheus snapshot and discard all raw metadata."""

    if type(body) is bytes:
        if len(body) > MAX_RESPONSE_BYTES:
            _fail("metrics_response_too_large")
        try:
            text = body.decode("utf-8", errors="strict")
        except UnicodeDecodeError:
            _fail("metrics_invalid_utf8")
    elif type(body) is str:
        try:
            encoded_size = len(body.encode("utf-8", errors="strict"))
        except UnicodeEncodeError:
            _fail("metrics_invalid_utf8")
        if encoded_size > MAX_RESPONSE_BYTES:
            _fail("metrics_response_too_large")
        text = body
    else:
        _fail("metrics_invalid_body_type")

    raw_lines = text.split("\n")
    if raw_lines and raw_lines[-1] == "":
        raw_lines.pop()
    if len(raw_lines) > MAX_LINES:
        _fail("metrics_too_many_lines")
    families: dict[str, dict[str, tuple[str, str, float]]] = {}
    recognized_samples = 0
    for raw_line in raw_lines:
        line = raw_line[:-1] if raw_line.endswith("\r") else raw_line
        if len(line.encode("utf-8")) > MAX_LINE_BYTES:
            _fail("metrics_line_too_long")
        stripped = line.strip(" \t")
        if not stripped or stripped.startswith("#"):
            continue
        name_match = _METRIC_NAME.match(stripped)
        if name_match is None:
            _fail("metrics_malformed_sample")
        # This is an allowlisted collector, not a general Prometheus parser.
        # Ignore unknown families before parsing their labels or numeric form;
        # exporters may legitimately expose unrelated NaN gauges or exemplars.
        if name_match.group(0) not in _RECOGNIZED_FAMILIES:
            continue
        name, labels, value = _parse_sample(stripped)
        recognized_samples += 1
        if recognized_samples > MAX_RECOGNIZED_SAMPLES:
            _fail("metrics_too_many_recognized_samples")
        _validate_value(name, value)
        identity = _series_identity(labels)
        scope_identity = _scope_identity(name, labels)
        finish_reason_class = _finish_reason_class(name, labels)
        family = families.setdefault(name, {})
        if identity in family:
            _fail("metrics_duplicate_series")
        family[identity] = (
            scope_identity,
            finish_reason_class,
            value,
        )

    frozen_families = tuple(
        (
            name,
            tuple(
                _Series(
                    identity=identity,
                    scope_identity=scope_identity,
                    finish_reason_class=finish_reason_class,
                    value=value,
                )
                for identity, (scope_identity, finish_reason_class, value)
                in sorted(series.items())
            ),
        )
        for name, series in sorted(families.items())
    )
    return MetricsSnapshot(
        recognized_samples=recognized_samples,
        available_families=tuple(sorted(families)),
        _families=frozen_families,
    )


def _selected_alias(
    snapshots: Sequence[MetricsSnapshot], aliases: Sequence[str]
) -> str | None:
    selected: list[str | None] = []
    for snapshot in snapshots:
        available = [
            name
            for name in aliases
            if MetricsSnapshot._family(snapshot, name) is not None
        ]
        selected.append(available[0] if available else None)
    if len(set(selected)) != 1:
        _fail("metrics_alias_or_availability_changed")
    return selected[0]


def _validate_snapshot(snapshot: MetricsSnapshot) -> None:
    """Reject forged or mutated snapshot shapes before any arithmetic."""

    if (
        type(snapshot) is not MetricsSnapshot
        or type(snapshot.recognized_samples) is not int
        or not 0 <= snapshot.recognized_samples <= MAX_RECOGNIZED_SAMPLES
        or type(snapshot.available_families) is not tuple
        or len(snapshot.available_families) > len(_RECOGNIZED_FAMILIES)
        or any(
            type(name) is not str
            for name in snapshot.available_families
        )
        or type(snapshot._families) is not tuple
        or len(snapshot._families) > snapshot.recognized_samples
    ):
        _fail("metrics_invalid_snapshot")
    names: list[str] = []
    sample_count = 0
    for entry in snapshot._families:
        if (
            type(entry) is not tuple
            or len(entry) != 2
            or type(entry[0]) is not str
            or entry[0] not in _RECOGNIZED_FAMILIES
            or type(entry[1]) is not tuple
            or not entry[1]
        ):
            _fail("metrics_invalid_snapshot")
        name, series = entry
        if (
            sample_count + len(series) > snapshot.recognized_samples
            or sample_count + len(series) > MAX_RECOGNIZED_SAMPLES
        ):
            _fail("metrics_invalid_snapshot")
        names.append(name)
        identities: list[str] = []
        for item in series:
            if (
                type(item) is not _Series
                or type(item.identity) is not str
                or re.fullmatch(r"[0-9a-f]{64}", item.identity) is None
                or type(item.scope_identity) is not str
                or re.fullmatch(
                    r"[0-9a-f]{64}", item.scope_identity
                ) is None
                or type(item.finish_reason_class) is not str
                or item.finish_reason_class not in _FINISH_REASON_CLASSES
                or (
                    name == _REQUESTS_FINISHED_FAMILY
                    and item.finish_reason_class == "not_applicable"
                )
                or (
                    name != _REQUESTS_FINISHED_FAMILY
                    and item.finish_reason_class != "not_applicable"
                )
                or type(item.value) is not float
                or not math.isfinite(item.value)
            ):
                _fail("metrics_invalid_snapshot")
            try:
                _validate_value(name, item.value)
            except MetricsCollectionError:
                _fail("metrics_invalid_snapshot")
            identities.append(item.identity)
        if identities != sorted(set(identities)):
            _fail("metrics_invalid_snapshot")
        sample_count += len(series)
    if (
        names != sorted(set(names))
        or tuple(names) != snapshot.available_families
        or sample_count != snapshot.recognized_samples
    ):
        _fail("metrics_invalid_snapshot")


def _validate_window(window: MetricsWindow) -> None:
    """Keep the collector's only public projection finite and allowlisted."""

    if (
        type(window) is not MetricsWindow
        or type(window.elapsed_seconds) is not float
        or not math.isfinite(window.elapsed_seconds)
        or not 0 < window.elapsed_seconds <= MAX_SAFE_NUMERIC_MAGNITUDE
        or type(window.observations) is not int
        or not 2 <= window.observations <= MAX_OBSERVATIONS + 2
        or type(window.scope) is not str
        or window.scope != _WINDOW_SCOPE
        or type(window.decision_effect) is not str
        or window.decision_effect != _WINDOW_DECISION_EFFECT
        or type(window.caveats) is not tuple
        or len(window.caveats) != len(_WINDOW_CAVEATS)
        or any(type(caveat) is not str for caveat in window.caveats)
        or window.caveats != _WINDOW_CAVEATS
        or type(window.source_families) is not tuple
        or len(window.source_families) > len(_RECOGNIZED_FAMILIES)
        or type(window.series_counts) is not tuple
        or type(window.histogram_observation_counts) is not tuple
        or (
            window.metric_scope_consistent is not None
            and type(window.metric_scope_consistent) is not bool
        )
        or (
            window.metric_scope_count is not None
            and (
                type(window.metric_scope_count) is not int
                or not 0
                <= window.metric_scope_count
                <= MAX_RECOGNIZED_SAMPLES
            )
        )
        or (
            (window.metric_scope_consistent is None)
            != (window.metric_scope_count is None)
        )
        or (
            window.metric_scope_consistent is True
            and window.metric_scope_count == 0
        )
    ):
        _fail("metrics_invalid_window")
    if (
        any(
            type(name) is not str or name not in _RECOGNIZED_FAMILIES
            for name in window.source_families
        )
        or window.source_families
        != tuple(sorted(set(window.source_families)))
    ):
        _fail("metrics_invalid_window")
    integer_values = (
        window.requests_finished,
        window.output_tokens,
        window.prompt_tokens,
        window.preemptions,
        window.max_requests_running,
        window.max_requests_waiting,
        window.max_requests_swapped,
        window.allowed_finished_requests,
        window.disallowed_finished_requests,
        window.unclassified_finished_requests,
    )
    if any(
        value is not None
        and (
            type(value) is not int
            or not 0 <= value <= MAX_SAFE_NUMERIC_MAGNITUDE
        )
        for value in integer_values
    ):
        _fail("metrics_invalid_window")
    float_values = (
        window.finished_requests_per_second,
        window.output_tokens_per_second,
        window.prompt_tokens_per_second,
        window.mean_ttft_ms,
        window.mean_tpot_ms,
        window.mean_inter_token_latency_ms,
        window.mean_e2e_ms,
        window.mean_queue_time_ms,
        window.mean_prefill_time_ms,
        window.mean_decode_time_ms,
        window.max_kv_cache_usage_fraction,
    )
    if any(
        value is not None
        and (
            type(value) is not float
            or not math.isfinite(value)
            or not 0 <= value <= MAX_SAFE_NUMERIC_MAGNITUDE
        )
        for value in float_values
    ):
        _fail("metrics_invalid_window")
    if (
        window.max_kv_cache_usage_fraction is not None
        and window.max_kv_cache_usage_fraction > 1
    ):
        _fail("metrics_invalid_window")
    allowed_count_names = {
        "requests_finished",
        "output_tokens",
        "prompt_tokens",
        "preemptions",
        "requests_running",
        "requests_waiting",
        "requests_swapped",
        "kv_cache_usage",
        *_HISTOGRAM_SUMS,
        *_HISTOGRAM_COUNTS,
    }
    if len(window.series_counts) > len(allowed_count_names):
        _fail("metrics_invalid_window")
    count_names: list[str] = []
    for item in window.series_counts:
        if (
            type(item) is not tuple
            or len(item) != 2
            or type(item[0]) is not str
            or item[0] not in allowed_count_names
            or type(item[1]) is not int
            or not 1 <= item[1] <= MAX_RECOGNIZED_SAMPLES
        ):
            _fail("metrics_invalid_window")
        count_names.append(item[0])
    if count_names != sorted(set(count_names)):
        _fail("metrics_invalid_window")
    if len(window.histogram_observation_counts) > len(
        _HISTOGRAM_OBSERVATION_NAMES
    ):
        _fail("metrics_invalid_window")
    observation_names: list[str] = []
    for item in window.histogram_observation_counts:
        if (
            type(item) is not tuple
            or len(item) != 2
            or type(item[0]) is not str
            or item[0] not in _HISTOGRAM_OBSERVATION_NAMES
            or type(item[1]) is not int
            or not 0 <= item[1] <= MAX_SAFE_NUMERIC_MAGNITUDE
        ):
            _fail("metrics_invalid_window")
        observation_names.append(item[0])
    if observation_names != sorted(set(observation_names)):
        _fail("metrics_invalid_window")
    outcome_counts = (
        window.allowed_finished_requests,
        window.disallowed_finished_requests,
        window.unclassified_finished_requests,
    )
    supplied_outcomes = tuple(value is not None for value in outcome_counts)
    if any(supplied_outcomes):
        if (
            not all(supplied_outcomes)
            or window.requests_finished is None
            or sum(value for value in outcome_counts if value is not None)
            != window.requests_finished
        ):
            _fail("metrics_invalid_window")
    elif window.requests_finished is None:
        return


def _metric_scope_summary(
    snapshot: MetricsSnapshot,
    sources: set[str],
) -> tuple[bool, int]:
    scope_sets: list[frozenset[str]] = []
    for family_name, series in snapshot._families:
        if family_name in sources:
            scope_sets.append(
                frozenset(item.scope_identity for item in series)
            )
    if len(scope_sets) != len(sources) or not scope_sets:
        return False, len(set().union(*scope_sets)) if scope_sets else 0
    first = scope_sets[0]
    return all(item == first for item in scope_sets[1:]), len(
        set().union(*scope_sets)
    )


def _counter_series_deltas(
    snapshots: Sequence[MetricsSnapshot], name: str | None
) -> Mapping[str, float] | None:
    if name is None:
        return None
    topology: set[str] | None = None
    first: Mapping[str, float] | None = None
    previous: Mapping[str, float] | None = None
    last: Mapping[str, float] | None = None
    metadata: Mapping[str, tuple[str, str]] | None = None
    for snapshot in snapshots:
        series = MetricsSnapshot._family(snapshot, name)
        if series is None:
            _fail("metrics_series_topology_changed")
        identities = set(series)
        if topology is None:
            topology = identities
        elif identities != topology:
            _fail("metrics_series_topology_changed")
        current_metadata: dict[str, tuple[str, str]] = {}
        for family_name, family_series in snapshot._families:
            if family_name == name:
                current_metadata = {
                    item.identity: (
                        item.scope_identity,
                        item.finish_reason_class,
                    )
                    for item in family_series
                }
                break
        if set(current_metadata) != identities:
            _fail("metrics_series_topology_changed")
        if metadata is None:
            metadata = MappingProxyType(current_metadata)
        elif current_metadata != metadata:
            _fail("metrics_series_topology_changed")
        if previous is not None and any(
            series[identity] < value
            for identity, value in previous.items()
        ):
            _fail("metrics_counter_reset")
        if first is None:
            first = series
        previous = series
        last = series
    if first is None or last is None:
        _fail("metrics_series_topology_changed")
    deltas = {
        identity: last[identity] - value for identity, value in first.items()
    }
    delta = sum(deltas.values())
    if not math.isfinite(delta) or delta > MAX_SAFE_NUMERIC_MAGNITUDE:
        _fail("metrics_derived_value_out_of_range")
    return MappingProxyType(deltas)


def _finished_request_outcome_counts(
    snapshots: Sequence[MetricsSnapshot],
    name: str | None,
) -> tuple[int | None, int | None, int | None]:
    if name is None:
        return None, None, None
    deltas = _counter_series_deltas(snapshots, name)
    if deltas is None:
        _fail("metrics_series_topology_changed")
    classes: dict[str, str] = {}
    for family_name, series in snapshots[0]._families:
        if family_name == name:
            classes = {
                item.identity: item.finish_reason_class for item in series
            }
            break
    if set(classes) != set(deltas):
        _fail("metrics_series_topology_changed")
    totals = {"allowed": 0.0, "disallowed": 0.0, "unclassified": 0.0}
    for identity, delta in deltas.items():
        outcome_class = classes[identity]
        if outcome_class not in totals:
            _fail("metrics_invalid_snapshot")
        totals[outcome_class] += delta
    return (
        _as_int(totals["allowed"]),
        _as_int(totals["disallowed"]),
        _as_int(totals["unclassified"]),
    )


def _counter_delta(
    snapshots: Sequence[MetricsSnapshot], name: str | None
) -> tuple[float | None, int]:
    deltas = _counter_series_deltas(snapshots, name)
    if deltas is None:
        return None, 0
    return sum(deltas.values()), len(deltas)


def _plain_family(
    snapshots: Sequence[MetricsSnapshot], name: str
) -> str | None:
    present = [
        MetricsSnapshot._family(snapshot, name) is not None
        for snapshot in snapshots
    ]
    if any(present) and not all(present):
        _fail("metrics_alias_or_availability_changed")
    return name if all(present) else None


def _histogram_base(
    snapshots: Sequence[MetricsSnapshot], base: str
) -> str | None:
    """Require a complete sum/count pair with stable availability."""

    pair_presence: list[bool] = []
    for snapshot in snapshots:
        has_sum = (
            MetricsSnapshot._family(snapshot, f"{base}_sum") is not None
        )
        has_count = (
            MetricsSnapshot._family(snapshot, f"{base}_count") is not None
        )
        if has_sum != has_count:
            _fail("metrics_histogram_pair_incomplete")
        pair_presence.append(has_sum)
    if len(set(pair_presence)) != 1:
        _fail("metrics_alias_or_availability_changed")
    return base if pair_presence[0] else None


def _histogram_mean_ms(
    snapshots: Sequence[MetricsSnapshot],
    base: str | None,
) -> tuple[float | None, tuple[tuple[str, int], ...], int | None]:
    if base is None:
        return None, (), None
    sum_deltas = _counter_series_deltas(snapshots, f"{base}_sum")
    count_deltas = _counter_series_deltas(snapshots, f"{base}_count")
    sum_start = MetricsSnapshot._family(snapshots[0], f"{base}_sum")
    count_start = MetricsSnapshot._family(snapshots[0], f"{base}_count")
    if (
        sum_start is None
        or count_start is None
        or set(sum_start) != set(count_start)
        or sum_deltas is None
        or count_deltas is None
        or set(sum_deltas) != set(count_deltas)
    ):
        _fail("metrics_histogram_series_mismatch")
    for identity, count_delta_for_series in count_deltas.items():
        if count_delta_for_series == 0 and sum_deltas[identity] != 0:
            _fail("metrics_histogram_delta_mismatch")
    sum_delta = sum(sum_deltas.values())
    count_delta = sum(count_deltas.values())
    if not count_delta.is_integer():
        _fail("metrics_histogram_delta_mismatch")
    observation_count = int(count_delta)
    sum_count = len(sum_deltas)
    count_count = len(count_deltas)
    if count_delta == 0:
        if sum_delta != 0:
            _fail("metrics_histogram_delta_mismatch")
        mean = None
    else:
        mean = (sum_delta / count_delta) * 1000.0
        if (
            not math.isfinite(mean)
            or mean < 0
            or mean > MAX_SAFE_NUMERIC_MAGNITUDE
        ):
            _fail("metrics_derived_value_out_of_range")
    return (
        mean,
        (
            (f"{base}_sum", sum_count),
            (f"{base}_count", count_count),
        ),
        observation_count,
    )


def _gauge_max(
    snapshots: Sequence[MetricsSnapshot], name: str | None, *, kv: bool = False
) -> tuple[float | None, int]:
    if name is None:
        return None, 0
    topology: set[str] | None = None
    maximum: float | None = None
    count = 0
    for snapshot in snapshots:
        series = MetricsSnapshot._family(snapshot, name)
        if series is None:
            _fail("metrics_series_topology_changed")
        identities = set(series)
        if topology is None:
            topology = identities
            count = len(identities)
        elif identities != topology:
            _fail("metrics_series_topology_changed")
        aggregate = max(series.values()) if kv else sum(series.values())
        maximum = aggregate if maximum is None else max(maximum, aggregate)
    return maximum, count


def _as_int(value: float | None) -> int | None:
    if value is None:
        return None
    if not value.is_integer() or value > MAX_SAFE_NUMERIC_MAGNITUDE:
        _fail("metrics_derived_value_out_of_range")
    return int(value)


def _rate(value: float | None, elapsed_seconds: float) -> float | None:
    if value is None:
        return None
    result = value / elapsed_seconds
    if (
        not math.isfinite(result)
        or result < 0
        or result > MAX_SAFE_NUMERIC_MAGNITUDE
    ):
        _fail("metrics_derived_value_out_of_range")
    return result


def derive_metrics_window(
    before: MetricsSnapshot,
    after: MetricsSnapshot,
    elapsed_seconds: float,
    *,
    observations: Sequence[MetricsSnapshot] = (),
) -> MetricsWindow:
    """Derive one label-aware server-wide window from bounded snapshots."""

    if type(elapsed_seconds) not in {int, float}:
        _fail("metrics_invalid_elapsed")
    if elapsed_seconds <= 0 or elapsed_seconds > MAX_SAFE_NUMERIC_MAGNITUDE:
        _fail("metrics_invalid_elapsed")
    if type(elapsed_seconds) is float and not math.isfinite(elapsed_seconds):
        _fail("metrics_invalid_elapsed")
    if not isinstance(before, MetricsSnapshot) or not isinstance(
        after, MetricsSnapshot
    ):
        _fail("metrics_invalid_snapshot")
    if type(observations) not in {tuple, list}:
        _fail("metrics_invalid_observations")
    if len(observations) > MAX_OBSERVATIONS:
        _fail("metrics_too_many_observations")
    observation_snapshots = tuple(observations)
    if any(
        type(item) is not MetricsSnapshot
        for item in observation_snapshots
    ):
        _fail("metrics_invalid_snapshot")
    elapsed = float(elapsed_seconds)
    all_snapshots = (before, *observation_snapshots, after)
    total_recognized_samples = 0
    for snapshot in all_snapshots:
        if (
            type(snapshot) is not MetricsSnapshot
            or type(snapshot.recognized_samples) is not int
            or not 0
            <= snapshot.recognized_samples
            <= MAX_RECOGNIZED_SAMPLES
        ):
            _fail("metrics_invalid_snapshot")
        total_recognized_samples += snapshot.recognized_samples
        if total_recognized_samples > MAX_WINDOW_RECOGNIZED_SAMPLES:
            _fail("metrics_window_too_large")
    for snapshot in all_snapshots:
        _validate_snapshot(snapshot)

    sources: set[str] = set()
    series_counts: dict[str, int] = {}

    def counter(logical: str, physical: str | None) -> float | None:
        if physical is None:
            return None
        delta, count = _counter_delta(all_snapshots, physical)
        sources.add(physical)
        series_counts[logical] = count
        return delta

    requests_name = _plain_family(
        all_snapshots, "vllm:request_success_total"
    )
    output_name = _plain_family(
        all_snapshots, "vllm:generation_tokens_total"
    )
    prompt_name = _plain_family(
        all_snapshots, "vllm:prompt_tokens_total"
    )
    preemption_name = _selected_alias(
        all_snapshots, _ALIASES["preemptions"]
    )
    requests_delta = counter("requests_finished", requests_name)
    (
        allowed_finished_requests,
        disallowed_finished_requests,
        unclassified_finished_requests,
    ) = _finished_request_outcome_counts(all_snapshots, requests_name)
    output_delta = counter("output_tokens", output_name)
    prompt_delta = counter("prompt_tokens", prompt_name)
    preemption_delta = counter("preemptions", preemption_name)

    histogram_specs = (
        ("ttft", "vllm:time_to_first_token_seconds"),
        ("e2e", "vllm:e2e_request_latency_seconds"),
        ("queue", "vllm:request_queue_time_seconds"),
        ("prefill", "vllm:request_prefill_time_seconds"),
        ("decode", "vllm:request_decode_time_seconds"),
    )
    histogram_means: dict[str, float | None] = {}
    histogram_observation_counts: dict[str, int] = {}
    for logical, base_name in histogram_specs:
        base = _histogram_base(all_snapshots, base_name)
        mean, counts, observation_count = _histogram_mean_ms(
            all_snapshots,
            base,
        )
        histogram_means[logical] = mean
        if base is not None:
            sources.update((f"{base}_sum", f"{base}_count"))
            series_counts.update(dict(counts))
            if observation_count is None:
                _fail("metrics_histogram_delta_mismatch")
            histogram_observation_counts[logical] = observation_count

    tpot_base = _histogram_base(
        all_snapshots, "vllm:request_time_per_output_token_seconds"
    )
    mean_tpot, tpot_counts, tpot_observations = _histogram_mean_ms(
        all_snapshots, tpot_base
    )
    if tpot_base is not None:
        sources.update((f"{tpot_base}_sum", f"{tpot_base}_count"))
        series_counts.update(dict(tpot_counts))
        if tpot_observations is None:
            _fail("metrics_histogram_delta_mismatch")
        histogram_observation_counts["tpot"] = tpot_observations

    itl_aliases = _ALIASES["itl"]
    itl_bases: list[str | None] = []
    for snapshot in all_snapshots:
        available: list[str] = []
        for base in itl_aliases:
            has_sum = (
                MetricsSnapshot._family(snapshot, f"{base}_sum")
                is not None
            )
            has_count = (
                MetricsSnapshot._family(snapshot, f"{base}_count")
                is not None
            )
            if has_sum != has_count:
                _fail("metrics_histogram_pair_incomplete")
            if has_sum:
                available.append(base)
        itl_bases.append(available[0] if available else None)
    if len(set(itl_bases)) != 1:
        _fail("metrics_alias_or_availability_changed")
    itl_base = itl_bases[0]
    mean_itl, itl_counts, itl_observations = _histogram_mean_ms(
        all_snapshots, itl_base
    )
    if itl_base is not None:
        sources.update((f"{itl_base}_sum", f"{itl_base}_count"))
        series_counts.update(dict(itl_counts))
        if itl_observations is None:
            _fail("metrics_histogram_delta_mismatch")
        histogram_observation_counts["itl"] = itl_observations

    running_name = _plain_family(
        all_snapshots, "vllm:num_requests_running"
    )
    waiting_name = _plain_family(
        all_snapshots, "vllm:num_requests_waiting"
    )
    swapped_name = _plain_family(
        all_snapshots, "vllm:num_requests_swapped"
    )
    kv_name = _selected_alias(all_snapshots, _ALIASES["kv_cache"])
    running_max, running_count = _gauge_max(all_snapshots, running_name)
    waiting_max, waiting_count = _gauge_max(all_snapshots, waiting_name)
    swapped_max, swapped_count = _gauge_max(all_snapshots, swapped_name)
    kv_max, kv_count = _gauge_max(all_snapshots, kv_name, kv=True)
    for logical, physical, count in (
        ("requests_running", running_name, running_count),
        ("requests_waiting", waiting_name, waiting_count),
        ("requests_swapped", swapped_name, swapped_count),
        ("kv_cache_usage", kv_name, kv_count),
    ):
        if physical is not None:
            sources.add(physical)
            series_counts[logical] = count

    scope_consistent, scope_count = _metric_scope_summary(
        before,
        sources,
    )

    return MetricsWindow(
        elapsed_seconds=elapsed,
        observations=len(all_snapshots),
        requests_finished=_as_int(requests_delta),
        output_tokens=_as_int(output_delta),
        prompt_tokens=_as_int(prompt_delta),
        preemptions=_as_int(preemption_delta),
        finished_requests_per_second=_rate(requests_delta, elapsed),
        output_tokens_per_second=_rate(output_delta, elapsed),
        prompt_tokens_per_second=_rate(prompt_delta, elapsed),
        mean_ttft_ms=histogram_means["ttft"],
        mean_tpot_ms=mean_tpot,
        mean_inter_token_latency_ms=mean_itl,
        mean_e2e_ms=histogram_means["e2e"],
        mean_queue_time_ms=histogram_means["queue"],
        mean_prefill_time_ms=histogram_means["prefill"],
        mean_decode_time_ms=histogram_means["decode"],
        max_requests_running=_as_int(running_max),
        max_requests_waiting=_as_int(waiting_max),
        max_requests_swapped=_as_int(swapped_max),
        max_kv_cache_usage_fraction=kv_max,
        source_families=tuple(sorted(sources)),
        series_counts=tuple(sorted(series_counts.items())),
        histogram_observation_counts=tuple(
            sorted(histogram_observation_counts.items())
        ),
        metric_scope_consistent=scope_consistent,
        metric_scope_count=scope_count,
        allowed_finished_requests=allowed_finished_requests,
        disallowed_finished_requests=disallowed_finished_requests,
        unclassified_finished_requests=unclassified_finished_requests,
    )


def _is_loopback(hostname: str) -> bool:
    if hostname.lower() == "localhost":
        return True
    try:
        return ipaddress.ip_address(hostname).is_loopback
    except ValueError:
        return False


def _validated_metrics_url(value: object) -> str:
    if (
        type(value) is not str
        or not value
        or len(value) > 2_048
        or value != value.strip()
        or any(
            ord(character) < 33 or ord(character) > 126
            for character in value
        )
        or "\\" in value
        or _ENCODED_CONTROL.search(value) is not None
    ):
        _fail("metrics_invalid_url")
    try:
        parsed: SplitResult = urlsplit(value)
        port = parsed.port
    except ValueError:
        _fail("metrics_invalid_url")
    if (
        parsed.scheme not in {"http", "https"}
        or not parsed.netloc
        or not parsed.hostname
        or parsed.username is not None
        or parsed.password is not None
        or "?" in value
        or "#" in value
        or "%" in parsed.path
        or (port is None and parsed.netloc.endswith(":"))
        or not parsed.path.startswith("/")
        or any(segment in {".", ".."} for segment in parsed.path.split("/"))
        or "*" in parsed.hostname
    ):
        _fail("metrics_invalid_url")
    try:
        ipaddress.ip_address(parsed.hostname)
    except ValueError:
        if _DNS_HOST.fullmatch(parsed.hostname) is None:
            _fail("metrics_invalid_url")
    if parsed.scheme == "http" and not _is_loopback(parsed.hostname):
        _fail("metrics_insecure_url")
    return value


class PrometheusMetricsCollector:
    """Fetch bounded snapshots from one explicit, operator-approved URL."""

    def __init__(
        self,
        metrics_url: str,
        *,
        transport: httpx.AsyncBaseTransport | None = None,
    ) -> None:
        self._metrics_url = _validated_metrics_url(metrics_url)
        self._transport = transport

    async def snapshot(self) -> MetricsSnapshot:
        """Perform one GET with no auth, redirect, proxy, or raw retention."""

        try:
            async with asyncio.timeout(SCRAPE_TIMEOUT_SECONDS):
                async with httpx.AsyncClient(
                    transport=self._transport,
                    timeout=httpx.Timeout(SCRAPE_TIMEOUT_SECONDS),
                    follow_redirects=False,
                    trust_env=False,
                    verify=True,
                    headers={
                        "Accept": "text/plain; version=0.0.4",
                        "Accept-Encoding": "identity",
                    },
                ) as client:
                    async with client.stream(
                        "GET", self._metrics_url
                    ) as response:
                        if 300 <= response.status_code < 400:
                            _fail("metrics_redirect_rejected")
                        if response.status_code != 200:
                            _fail("metrics_http_status")
                        encoding = response.headers.get(
                            "content-encoding", "identity"
                        ).strip().lower()
                        if encoding not in {"", "identity"}:
                            _fail("metrics_content_encoding_rejected")
                        content_type = response.headers.get(
                            "content-type", ""
                        )
                        media_type = content_type.split(
                            ";", 1
                        )[0].strip().lower()
                        if media_type != "text/plain":
                            _fail("metrics_content_type_rejected")
                        content_length = response.headers.get(
                            "content-length"
                        )
                        if content_length is not None:
                            try:
                                declared_length = int(content_length)
                            except ValueError:
                                _fail("metrics_invalid_content_length")
                            if (
                                declared_length < 0
                                or declared_length > MAX_RESPONSE_BYTES
                            ):
                                _fail("metrics_response_too_large")
                        body = bytearray()
                        async for chunk in response.aiter_raw():
                            if len(body) + len(chunk) > MAX_RESPONSE_BYTES:
                                _fail("metrics_response_too_large")
                            body.extend(chunk)
        except MetricsCollectionError:
            raise
        except (TimeoutError, httpx.TimeoutException):
            _fail("metrics_timeout")
        except (httpx.HTTPError, httpx.StreamError, httpx.InvalidURL):
            _fail("metrics_transport_error")
        return parse_vllm_metrics(bytes(body))


__all__ = [
    "MAX_LABELS_PER_SAMPLE",
    "MAX_LINES",
    "MAX_LINE_BYTES",
    "MAX_OBSERVATIONS",
    "MAX_RECOGNIZED_SAMPLES",
    "MAX_RESPONSE_BYTES",
    "MAX_WINDOW_RECOGNIZED_SAMPLES",
    "MetricsCollectionError",
    "MetricsSnapshot",
    "MetricsWindow",
    "PrometheusMetricsCollector",
    "derive_metrics_window",
    "parse_vllm_metrics",
]
